https://habr.com/ru/post/176069/
1) change prive from string to int (but manually, migration didn't work, because postgres didn't resolve some types:

PM> enable-migrations
More than one context type was found in the assembly 'Apartments'.
To enable migrations for 'Apartments.Models.ApartmentsContext', use Enable-Migrations -ContextTypeName Apartments.Models.ApartmentsContext.
To enable migrations for 'Apartments.Models.ApartmentsTemporaryContext', use Enable-Migrations -ContextTypeName Apartments.Models.ApartmentsTemporaryContext.
PM> Enable-Migrations -ContextTypeName Apartments.Models.ApartmentsTemporaryContext
Checking if the context targets an existing database...
Code First Migrations enabled for project Apartments.
PM> Add-Migration "change string Price to IntPrice in rubles"
Scaffolding migration 'change string Price to IntPrice in rubles'.
The Designer Code for this migration file includes a snapshot of your current Code First model. This snapshot is used to calculate the changes to your model when you scaffold the next migration. If you make additional changes to your model that you want to include in this migration, then you can re-scaffold it by running 'Add-Migration change string Price to IntPrice in rubles' again.
PM> Update-Database
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [201910160942372_change string Price to IntPrice in rubles].
Applying explicit migration: 201910160942372_change string Price to IntPrice in rubles.
System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Npgsql.PostgresException,Npgsql, Version=4.0.7.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Type is not resolved for member 'Npgsql.PostgresException,Npgsql, Version=4.0.7.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
PM> Update-Database -Verbose
Using StartUp project 'Apartments'.
Using NuGet project 'Apartments'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Target database is: 'ApartmentsDBv2' (DataSource: tcp://localhost:5432, Provider: Npgsql, Origin: Configuration).
Applying explicit migrations: [201910160942372_change string Price to IntPrice in rubles].
Applying explicit migration: 201910160942372_change string Price to IntPrice in rubles.
CREATE TABLE "public"."Adress"("Id" serial4 NOT NULL,"Street" text NOT NULL,"Country" text NOT NULL,"City" text NOT NULL,"PlaceName" text,"Traffic" float8 NOT NULL,"District" text,"MetroLine" text,"GeoLong" float8 NOT NULL,"GeoLat" float8 NOT NULL,"Information" text,"Comment" text,CONSTRAINT "PK_public.Adress" PRIMARY KEY ("Id"))
System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Npgsql.PostgresException,Npgsql, Version=4.0.7.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Type is not resolved for member 'Npgsql.PostgresException,Npgsql, Version=4.0.7.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
PM> Update-Database -Verbose
Using StartUp project 'Apartments'.
Using NuGet project 'Apartments'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Target database is: 'ApartmentsDBv2' (DataSource: tcp://localhost:5432, Provider: Npgsql, Origin: Configuration).
Applying explicit migrations: [201910160942372_change string Price to IntPrice in rubles].
Applying explicit migration: 201910160942372_change string Price to IntPrice in rubles.
CREATE TABLE "public"."Apartment"("Id" serial4 NOT NULL,"Name" text NOT NULL,"AuthorId" text NOT NULL,"IntPrice" int4 NOT NULL,"Phone" text NOT NULL,"Description" text NOT NULL,"DateCreated" timestamp,"DateActualTo" timestamp,"IsActive" boolean NOT NULL,"IsDonated" boolean NOT NULL,"DonateDueDate" timestamp,"FollowersIds" text,"AddressId" text NOT NULL,"ParsingSource" int4,"ShortId" text,"SourceURL" text,"mainPhotoUrl" text,"photosListUrls" text,"phoneImgURL" text,"Comment" text,"Information" text,CONSTRAINT "PK_public.Apartment" PRIMARY KEY ("Id"))
System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Npgsql.PostgresException,Npgsql, Version=4.0.7.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Type is not resolved for member 'Npgsql.PostgresException,Npgsql, Version=4.0.7.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.